camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: abc
  filter:
    create: All tasks
  database:
     type: postgres
  process-engine-name: default   
spring:
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test1234
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  level:
    org.springframework: ERROR
    org.camunda.bpm.fileingest: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
     

